version: '3.8'

services:
  dagster:
    build: .
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /dagster_home
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dagster
    volumes:
      - ./dagster_home:/dagster_home
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: